"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "bn";

interface LanguageContextType {
    language: Language;
    toggleLanguage: () => void;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation & General
        dashboard: "Dashboard",
        clients: "Clients",
        services: "Services",
        billing: "Billing",
        support: "Support",
        reseller: "Reseller",
        settings: "Settings",
        logout: "Logout",
        search: "Search...",
        notifications: "Notifications",
        welcome_back: "Welcome back",
        hello: "Hello",
        hello_user: "Hello",
        manage: "Manage",
        status: "Status",
        date: "Date",
        amount: "Amount",
        total: "Total",
        subtotal: "Subtotal",
        discount: "Discount",
        promo_code: "Promo Code",
        apply: "Apply",
        details: "Details",
        active: "Active",
        loading: "Loading",
        search_placeholder: "Search...",
        filter: "Filter",
        retry: "Retry",
        view_all: "View All",
        actions: "Actions",
        reply: "Reply",
        completed: "Completed",
        cancelled: "Cancelled",
        pending: "Pending",
        paid: "Paid",
        unpaid: "Unpaid",

        // Admin Dashboard
        command_center: "Command Center",
        operational_intelligence: "Real-time operational intelligence and financial performance.",
        total_revenue: "Total Revenue",
        active_services: "Active Services",
        pending_orders: "Pending Orders",
        open_tickets: "Open Tickets",
        revenue_growth: "Revenue Growth",
        monthly_performance: "Monthly revenue performance",
        monthly: "Monthly",
        client_distribution: "Client Distribution",
        client_segments: "Client status segments",
        system_activity: "System Activity",
        quick_actions: "Quick Actions",
        add_client: "Add Client",
        create_invoice: "Create Invoice",
        new_ticket: "New Ticket",
        system_config: "System Config",
        notice_board: "Notice Board",
        maintenance_notice: "Scheduled system maintenance on Sunday, Jan 15th at 02:00 UTC. Expect 15 mins of downtime.",
        admin_panel: "Admin Panel",
        client_area: "Client Area",

        // Admin Billing
        admin_billing_desc: "Manage invoices, transactions, and gateways.",
        invoice_num: "Invoice #",
        overdue_invoices: "Overdue Invoices",
        immediate_attention: "Requires immediate attention",
        paid_this_month: "Paid This Month",
        revenue_collected: "Revenue collected",
        automation: "Automation",
        invoice_generation: "Invoice Generation",
        process_recurring: "Process all due recurring services.",
        generate_due_invoices: "Generate Due Invoices",
        cc_capture: "CC Capture",
        attempt_capture_desc: "Attempt to capture payment for due invoices.",
        attempt_cc_capture: "Attempt CC Captures",
        process_log: "Process Log",
        billing_tax: "Billing & Tax",
        billing_financials: "Billing & Financials",
        financial_standing: "Clear overview of your account's financial standing and historical invoices.",
        invoice_ref: "Invoice Reference",
        issuance_date: "Issuance Date",
        commercial_total: "Commercial Total",
        stored_credit: "Stored Credit",
        add_funds: "Add Funds / Credits",
        search_invoice_placeholder: "Search by Invoice ID...",
        automation_policy: "Automation Policy",
        automation_desc: "Enable automated credit capture to ensure zero downtime for your active infrastructure and services.",
        configure_autoplay: "Configure Auto-Pay",
        billing_inquiries: "Billing Inquiries",
        billing_inquiries_desc: "Have a question regarding an invoice? Our billing department is available 24/7 to resolve any discrepancies or payment issues.",
        open_billing_ticket: "Open Billing Ticket",

        // Admin Support
        admin_support_desc: "Manage tickets and network status.",
        awaiting_reply: "Awaiting Reply",
        on_hold: "On Hold",
        closed: "Closed",
        ticket_queue: "Ticket Queue",
        network_issues: "Network Issues",
        all_systems_operational: "All Systems Operational",
        no_network_incidents: "No active network incidents reported.",
        create_incident: "Create Incident",
        support_center: "Support Center",
        experts_ready: "Our experts are ready to help you thrive.",
        open_new_ticket: "Open New Ticket",
        search_tickets_placeholder: "Search by keyword or ticket ID...",
        systems_online: "Systems Online",
        priority_support: "Priority Support Active",
        guaranteed_response: "Your response time is guaranteed under 2 hours.",
        system_announcement: "System Announcement",
        view_details: "View Details",
        ticket_info: "Ticket Information",
        last_activity: "Last Activity",
        retrieving_history: "Retrieving your communication history...",
        no_active_tickets: "No active tickets",
        no_tickets_desc: "You don't have any support inquiries yet.",
        open_first_ticket: "Open your first ticket",

        // Admin Reports
        admin_reports_desc: "System analytics and income reports.",
        export_data: "Export Data",
        total_clients: "Total Clients",
        monthly_growth: "Monthly Growth",
        revenue_breakdown: "Revenue Breakdown",
        client_acquisition: "Client Acquisition",
        this_month: "This Month",
        last_month: "Last Month",
        avg_month: "Average/Month",
        reports: "Reports",

        // Client Management
        client_base_management: "Manage and search your client base.",
        add_new_client: "Add New Client",
        search_clients_placeholder: "Search by name, email or company...",
        client_name: "Client Name",
        contact: "Contact",
        created: "Created",
        view_profile: "View Profile",
        registered: "Registered",
        client_id: "Client ID",
        email_address: "Email Address",
        no_clients_found: "No clients found.",
        view_all_clients: "View All Clients",
        client_groups: "Client Groups",

        // Order & Product Mgmt
        order_management: "Order Management",
        process_orders: "Review and process incoming service orders.",
        order_info: "Order Information",
        client_service: "Client & Service",
        revenue: "Revenue",
        all_orders: "All Orders",
        search_orders_placeholder: "Search by ID, Client, Domain...",
        fraud: "Fraud",
        orders: "Orders",
        user_management: "User Management",
        internal_requests: "Internal Requests",
        resellers: "Resellers",
        bulk_setup: "Bulk Setup",
        investors: "Investors",
        manage_investors: "Manage Investors",
        withdrawals: "Withdrawals",
        sales_team: "Sales Team",
        sales_overview: "Sales Overview",
        verifications: "Verifications",
        client_relations: "Client Relations",
        client_crm: "Client CRM",
        merchandise: "Merchandise",
        active_services_sidebar: "Active Services",
        order_history: "Order History",
        invoices_and_billing: "Invoices & Billing",
        product_catalog: "Product Catalog",
        white_label_config: "White-Label Config",
        help_and_support: "Help & Support",
        switch_to_client_view: "Switch to Client View",
        my_commissions: "My Commissions",
        back_to_reseller: "Back to Reseller",
        profile: "Profile",
        add_service: "Add Service",
        list_all_services: "All Services",
        expiring_services: "Expiring Soon",
        support_tickets: "Support Tickets",
        network_issues_menu: "Network Status",
        predefined_replies: "Predefined Replies",
        refunds: "Refunds",
        product_management: "Manage your hosting plans, domains, and global inventory.",
        create_product: "Create Product",
        product_name: "Product Name",
        price: "Price",
        stock: "Stock",
        list_all_orders: "List All Orders",
        add_new_order: "Add New Order",
        invoices: "Invoices",
        transactions: "Transactions",
        billable_items: "Billable Items",
        quotes: "Quotes",

        // Products
        products: "Products",
        view_all_products: "View All Products",
        add_new_product: "Add New Product",
        categories: "Categories",
        add_category: "Add Category",
        product_description: "Manage your product catalog and services.",
        category_name: "Category Name",
        stock_control: "Stock Control",
        taxable: "Taxable",

        // Services & Hosting
        my_services: "My Services",
        services_hub: "Central hub for your active hosting packages and servers.",
        product_service: "Product / Service",
        pricing: "Pricing",
        next_due_date: "Next Due Date",
        order_new_service: "Order New Service",
        find_service_placeholder: "Find a service...",
        shared_hosting: "Shared Hosting",
        reseller_accounts: "Reseller Accounts",
        vps_servers: "VPS/Servers",
        hosting_plans: "Hosting Plans",
        domain_registration: "Domain Registration",
        domains: "Domains",
        hosting: "Hosting",
        list_all_domains: "List All Domains",
        register_domain: "Register Domain",
        expiring_domains: "Expiring Domains",
        tld_pricing: "TLD Pricing",
        my_domains: "My Domains",
        buy_new_domain: "Buy New Domain",
        domain_name: "Domain Name",
        registration_date: "Registration Date",
        expiry_date: "Expiry Date",
        search_domains_placeholder: "Search domains...",

        // Infrastructure
        infrastructure: "Infrastructure",
        asset_inventory: "Asset Inventory",
        provision_new: "Add New Service",
        active_nodes: "Active Nodes",
        system_load: "System Load",
        deployment_core: "Deployment Core",

        // Store & Cart
        store: "Store",
        cart: "Cart",
        checkout: "Checkout",

        add_to_cart: "Add to Cart",
        buy_now: "Buy Now",
        empty_cart: "Your cart is empty",
        order_summary: "Order Summary",
        complete_order: "Complete Order",
        new_arrivals: "New Arrivals",
        next_gen: "Next-Gen",
        cloud: "Cloud",
        power_digital_future: "Power your digital future with enterprise-grade hosting and seamless domain management.",
        review_cart: "Review Cart",
        secure_checkout_guaranteed: "Secure checkout guaranteed",
        starting_at: "Starting at",
        mo: "/mo",
        initializing_catalog: "Initializing Catalog...",
        inventory_items: "Inventory Items",
        billing_identity: "Billing Identity",
        verify_profile_provisioning: "Verify your profile information for automated service setup.",
        account_holder: "Account Holder",
        email_nexus: "Email Nexus",
        corporate_org: "Corporate/Organization",
        leave_blank_individual: "Leave blank for individual use",
        nexus_address: "Nexus Address (Billing)",
        global_hq: "Global HQ or Residential Address",
        automated_kyc: "Automated KYC Recognition",
        identity_preverified: "Your identity is pre-verified. No further document submission required for this order.",
        select_protocol: "Select Transaction Protocol",
        credit_interface: "Credit Interface",
        instant_deployment: "Visa, Mastercard, AMEX • Instant Deployment",
        mobile_gateway: "Mobile Gateway",
        bkash_stripe_oneclick: "bKash, Nagad, Stripe Mobile • 1-Click Payment",
        encrypted_lock: "End-to-End Encrypted",
        authorize_resources: "By proceeding, you authorize WHMCS Fusion to initialize the requested resources immediately.",
        deploy_assets_now: "Deploy Assets Now",
        refine_details: "Refine Details",
        deployment_initialized: "Deployment Initialized",
        order_broadcast: "Order has been broadcast to our activation engines.",
        workspace_home: "Workspace Home",
        manage_assets: "Manage Assets",
        financial_overview: "Financial Overview",
        net_payable: "Net Payable",
        promo_credentials: "Promotion Credentials",
        voucher_promo: "Voucher or Promo...",
        pci_compliant: "PCI-DSS Compliant Gateway",
        ssl_secure: "SSL Secure Certificates",
        secure_transaction: "Secure Transaction",
        finalize_your: "Finalize Your",
        moments_away_deploy: "You are moments away from deploying your cloud workspace.",
        add_premium_infra: "Add some premium infrastructure to your inventory to proceed with checkout.",
        browse_store: "Browse Store",
        tax_vat: "Tax/VAT",
        scheduled_maintenance_maintenance: "Scheduled network upgrades in the Tokyo region on Jan 5th. No impact expected.",
        // Reseller
        reseller_dashboard: "Reseller Dashboard",
        reseller_center: "Reseller Center",
        commissions: "Commissions",
        payouts: "Payouts",
        white_label: "White Label",
        treasury: "Treasury",
        payout_requests: "Payout Requests",
        available_balance: "Available Balance",
        bdt: "BDT",
        taka: "Taka",
        withdraw_funds: "Withdraw Funds",
        payout_history: "Payout History",

        // Settings & Security
        branding_settings: "Branding Settings",
        visual_identity: "Visual Identity",
        interface_personality: "Interface Personality",
        theme_modes: "Theme Modes",
        media_assets: "Media Assets",
        domain_seo: "Domain & SEO",
        custom_dev: "Custom Dev",
        live_preview: "Live Preview",
        system_configuration: "System Configuration",
        general: "General",
        security: "Security",
        my_profile: "My Profile",
        audit_history: "Audit History",
        audit_history_desc: "Audit history of your account.",

        // Utilities & Security (Sidebar)
        utilities: "Utilities",
        whois_lookup: "WHOIS Lookup",
        dns_resolver: "DNS Resolver",
        tld_sync: "TLD Sync",
        activity_logs: "Activity Logs",
        banned_ips: "Banned IPs",
        security_questions: "Security Questions",

        // Activity Logs
        activity_protocol: "Activity Protocol",
        technical_narrative: "Technical Narrative",
        author: "Author",
        timestamp: "Timestamp",
        trace: "Trace",
        log_engine_desc: "Immutable chronological record of all administrative and system-wide intelligence.",
        search_logs_placeholder: "Search by action, user, or IP...",
        advanced_filters: "Advanced Filters",
        aggregating_logs: "Aggregating Global Activity Protocols...",
        activity_stream: "Activity Stream",
        // Public Pages & Landing
        home: "Home",
        about_us: "About Us",
        contact_us: "Contact Us",
        privacy_policy: "Privacy Policy",
        terms_of_service: "Terms of Service",
        features: "Features",
        testimonials: "Testimonials",
        faq: "FAQ",
        get_started: "Get Started",
        learn_more: "Learn More",

        // Hero Section
        hero_title_1: "Build Your Digital",
        hero_title_accent: "Empire Today",
        hero_subtitle: "Premium Web Hosting, VPS, and Dedicated Servers with 99.9% Uptime Guarantee and 24/7 Expert Support.",
        hero_search_placeholder: "Find your perfect domain name...",
        hero_search_btn: "Search",
        retention_reputation: "Retention is our Reputation: Long-standing loyal client base is our biggest proof.",
        verify_buy: "Verify: Check Live Benchmark reports, Backup system—then decide.",
        professional_support: "Professional Support is our Impression",

        // Service Group
        choose_solution: "Choose Your Hosting Solution",
        solution_desc: "Select a category to view our competitive pricing plans designed for speed and reliability.",
        plans_available: "Plans Available",
        see_plans: "See Plans",
        back_to_categories: "Back to Categories",
        no_plans_available: "No plans currently available in this category.",

        // Pricing Card
        order_now: "Order Now",
        starter_journey: "Perfect for starting your journey",

        // Features Section
        why_choose_us: "Why Choose Us",
        why_choose_desc: "We provide the best hosting solutions with enterprise-grade infrastructure.",
        feature_speed_title: "Fast BDIX-optimized NVMe",
        feature_speed_desc: "BDIX-optimized NVMe SSD storage ensure your website loads instantly for local visitors.",
        feature_security_title: "Ironclad Security",
        feature_security_desc: "Advanced DDoS protection, Imunify360, and automated hourly database backups.",
        feature_support_title: "Professional Support",
        feature_support_desc: "Engineers, not just support agents, available 24/7 in Bangla & English.",
        feature_uptime_title: "Transparent Uptime",
        feature_uptime_desc: "We provide live benchmark reports so you can see our real-world performance.",

        // Testimonials
        trusted_by: "Trusted by Developers",
        testimonial_1: "Best hosting provider I have ever used. Support is top notch!",
        testimonial_2: "Migrating was super easy and my site is 3x faster now.",

        // FAQ
        faq_title: "Frequently Asked Questions",
        faq_1_q: "How long does it take to activate?",
        faq_1_a: "Most services are activated instantly after payment confirmation.",
        faq_2_q: "Can I upgrade my plan later?",
        faq_2_a: "Yes, you can upgrade or downgrade your plan at any time from the client area.",
        faq_3_q: "Do you offer money-back guarantee?",
        faq_3_a: "Yes, we offer a 30-day money-back guarantee on all shared hosting plans.",

        // Contact Page
        get_in_touch: "Get in Touch",
        contact_desc: "Have questions? We are here to help.",
        send_message: "Send Message",
        your_name: "Your Name",
        your_email: "Your Email",
        subject: "Subject",
        message: "Message",
        address: "Address",
        phone: "Phone",

        // Legal
        last_updated: "Last Updated",
    },
    bn: {
        // Navigation & General
        dashboard: "ড্যাশবোর্ড",
        clients: "ক্লায়েন্ট",
        services: "সার্ভিস",
        billing: "বিলিং",
        support: "সাপোর্ট",
        reseller: "রিসেলার",
        settings: "সেটিংস",
        logout: "লগ আউট",
        search: "খুঁজুন...",
        notifications: "বিজ্ঞপ্তি",
        welcome_back: "স্বাগতম",
        hello: "হ্যালো",
        hello_user: "হ্যালো",
        manage: "পরিচালনা",
        status: "অবস্থা",
        date: "তারিখ",
        amount: "পরিমাণ",
        total: "মোট",
        subtotal: "উপমোট",
        discount: "ছাড়",
        promo_code: "প্রোমো কোড",
        apply: "প্রয়োগ করুন",
        details: "বিস্তারিত",
        active: "সক্রিয়",
        loading: "লোড হচ্ছে",
        search_placeholder: "খুঁজুন...",
        filter: "ফিল্টার",
        retry: "আবার চেষ্টা করুন",
        view_all: "সব দেখুন",
        actions: "অ্যাকশন",
        reply: "উত্তর দিন",
        completed: "সম্পন্ন",
        cancelled: "বাতিল",
        pending: "অপেক্ষমান",
        paid: "পরিশোধিত",
        unpaid: "অপরিশোধিত",

        // Admin Dashboard
        command_center: "কমান্ড সেন্টার",
        operational_intelligence: "রিয়েল-টাইম অপারেশনাল ইন্টেলিজেন্স এবং আর্থিক কর্মক্ষমতা।",
        total_revenue: "মোট রাজস্ব",
        active_services: "সক্রিয় সার্ভিস",
        pending_orders: "অপেক্ষমান অর্ডার",
        open_tickets: "খোলা টিকেট",
        revenue_growth: "রাজস্ব বৃদ্ধি",
        monthly_performance: "মাসিক রাজস্ব কর্মক্ষমতা",
        monthly: "মাসিক",
        client_distribution: "ক্লায়েন্ট ডিস্ট্রিবিউশন",
        client_segments: "ক্লায়েন্ট স্ট্যাটাস সেগমেন্ট",
        system_activity: "সিস্টেম কার্যকলাপ",
        quick_actions: "দ্রুত অ্যাকশন",
        add_client: "ক্লায়েন্ট যোগ করুন",
        create_invoice: "ইনভয়েস তৈরি করুন",
        new_ticket: "নতুন টিকেট",
        system_config: "সিস্টেম কনফিগারেশন",
        notice_board: "নোটিশ বোর্ড",
        maintenance_notice: "আগামী রবিবার, ১৫ই জানুয়ারি ০২:০০ ইউটিসি-তে নির্ধারিত সিস্টেম রক্ষণাবেক্ষণ। ১৫ মিনিটের ডাউনটাইম প্রত্যাশিত।",
        no_recent_activity: "সাম্প্রতিক কোন কার্যক্রম নেই",
        admin_panel: "অ্যাডমিন প্যানেল",
        client_area: "ক্লায়েন্ট এরিয়া",

        // Admin Billing
        admin_billing_desc: "ইনভয়েস, লেনদেন এবং গেটওয়ে পরিচালনা করুন।",
        invoice_num: "ইনভয়েস #",
        overdue_invoices: "ওভারডিউ ইনভয়েস",
        immediate_attention: "অবিলম্বে মনোযোগ প্রয়োজন",
        paid_this_month: "এই মাসে পরিশোধিত",
        revenue_collected: "সংগৃহীত রাজস্ব",
        automation: "অটোমেশন",
        invoice_generation: "ইনভয়েস তৈরি",
        process_recurring: "সমস্ত প্রদেয় পৌনঃপুনিক পরিষেবা প্রক্রিয়া করুন।",
        generate_due_invoices: "প্রদেয় ইনভয়েস তৈরি করুন",
        cc_capture: "সিসি ক্যাপচার",
        attempt_capture_desc: "প্রদেয় ইনভয়েসের জন্য পেমেন্ট ক্যাপচার করার চেষ্টা করুন।",
        attempt_cc_capture: "সিসি ক্যাপচার চেষ্টা করুন",
        process_log: "প্রক্রিয়া লগ",
        billing_tax: "বিলিং এবং ট্যাক্স",
        billing_financials: "বিলিং এবং আর্থিক তথ্য",
        financial_standing: "আপনার অ্যাকাউন্টের আর্থিক অবস্থা এবং ঐতিহাসিক ইনভয়েসগুলোর পরিষ্কার ধারণা।",
        invoice_ref: "ইনভয়েস রেফারেন্স",
        issuance_date: "ইস্যু তারিখ",
        commercial_total: "মোট বাণিজ্যিক মূল্য",
        stored_credit: "জমা ক্রেডিট",
        add_funds: "ফান্ড / ক্রেডিট যোগ করুন",
        search_invoice_placeholder: "ইনভয়েস আইডি দিয়ে খুঁজুন...",
        automation_policy: "অটোমেশন পলিসি",
        automation_desc: "আপনার সক্রিয় পরিকাঠামো এবং পরিষেবাগুলোর জন্য জিরো ডাউনটাইম নিশ্চিত করতে স্বয়ংক্রিয় ক্রেডিট ক্যাপচার সক্ষম করুন।",
        configure_autoplay: "অটো-পে কনফিগার করুন",
        billing_inquiries: "বিলিং ইনকোয়ারি",
        billing_inquiries_desc: "ইনভয়েস সম্পর্কে কোনো প্রশ্ন আছে? যেকোনো অসঙ্গতি বা পেমেন্ট সমস্যা সমাধানের জন্য আমাদের বিলিং বিভাগ ২৪/৭ উপলব্ধ।",
        open_billing_ticket: "বিলিং টিকেট খুলুন",

        // Admin Support
        admin_support_desc: "টিকেট এবং নেটওয়ার্ক স্ট্যাটাস পরিচালনা করুন।",
        awaiting_reply: "উত্তরের অপেক্ষায়",
        on_hold: "হোল্ডে আছে",
        closed: "বন্ধ",
        ticket_queue: "টিকেট কিউ",
        network_issues: "নেটওয়ার্ক সমস্যা",
        all_systems_operational: "সমস্ত সিস্টেম সচল",
        no_network_incidents: "কোনো সক্রিয় নেটওয়ার্ক ঘটনা রিপোর্ট করা হয়নি।",
        create_incident: "ঘটনা তৈরি করুন",
        support_center: "সাপোর্ট সেন্টার",
        experts_ready: "আমাদের বিশেষজ্ঞরা আপনাকে সাহায্য করার জন্য প্রস্তুত।",
        open_new_ticket: "নতুন টিকেট খুলুন",
        search_tickets_placeholder: "কিওয়ার্ড বা টিকেট আইডি দিয়ে খুঁজুন...",
        systems_online: "সিস্টেম অনলাইন",
        priority_support: "প্রায়োরিটি সাপোর্ট সক্রিয়",
        guaranteed_response: "আপনার রেসপন্স টাইম ২ ঘন্টার নিচে গ্যারান্টিড।",
        system_announcement: "সিস্টেম ঘোষণা",
        view_details: "বিস্তারিত দেখুন",
        ticket_info: "টিকেটের তথ্য",
        last_activity: "শেষ কার্যকলাপ",
        retrieving_history: "আপনার যোগাযোগের ইতিহাস আনা হচ্ছে...",
        no_active_tickets: "কোনো সক্রিয় টিকেট নেই",
        no_tickets_desc: "আপনার এখনও কোনো সাপোর্ট ইনকোয়ারি নেই।",
        open_first_ticket: "আপনার প্রথম টিকেট খুলুন",

        // Admin Reports
        admin_reports_desc: "সিস্টেম বিশ্লেষণ এবং আয় রিপোর্ট।",
        export_data: "ডেটা এক্সপোর্ট করুন",
        total_clients: "মোট ক্লায়েন্ট",
        monthly_growth: "মাসিক বৃদ্ধি",
        revenue_breakdown: "রাজস্ব ব্রেকডাউন",
        client_acquisition: "ক্লায়েন্ট অর্জন",
        this_month: "এই মাস",
        last_month: "গত মাস",
        avg_month: "গড়/মাস",
        reports: "রিপোর্ট",

        // Client Management
        client_base_management: "আপনার ক্লায়েন্ট বেস পরিচালনা এবং অনুসন্ধান করুন।",
        add_new_client: "নতুন ক্লায়েন্ট যোগ করুন",
        search_clients_placeholder: "নাম, ইমেল বা কোম্পানি দিয়ে খুঁজুন...",
        client_name: "ক্লায়েন্ট নাম",
        contact: "যোগাযোগ",
        created: "তৈরি করা হয়েছে",
        view_profile: "প্রোফাইল দেখুন",
        registered: "নিবন্ধিত",
        client_id: "ক্লায়েন্ট আইডি",
        email_address: "ইমেল ঠিকানা",
        no_clients_found: "কোনো ক্লায়েন্ট পাওয়া যায়নি।",
        view_all_clients: "সব ক্লায়েন্ট দেখুন",
        client_groups: "ক্লায়েন্ট গ্রুপ",

        // Order & Product Mgmt
        order_management: "অর্ডার ম্যানেজমেন্ট",
        process_orders: "আগত সার্ভিস অর্ডারগুলো পর্যালোচনা এবং প্রক্রিয়া করুন।",
        order_info: "অর্ডার তথ্য",
        client_service: "ক্লায়েন্ট এবং সার্ভিস",
        revenue: "রাজস্ব",
        all_orders: "সব অর্ডার",
        search_orders_placeholder: "আইডি, ক্লায়েন্ট, ডোমেইন দিয়ে খুঁজুন...",
        fraud: "ফ্রড",
        orders: "অর্ডার",
        user_management: "ইউজার ম্যানেজমেন্ট",
        internal_requests: "অভ্যন্তরীণ অনুরোধ",
        resellers: "রিসেলার",
        bulk_setup: "বাল্ক সেটআপ",
        investors: "বিনিয়োগকারী",
        manage_investors: "বিনিয়োগকারী পরিচালনা",
        withdrawals: "উত্তোলন",
        sales_team: "সেলস টিম",
        sales_overview: "সেলস ওভারভিউ",
        verifications: "যাচাইকরণ",
        client_relations: "ক্লায়েন্ট রিলেশন",
        client_crm: "ক্লায়েন্ট সিআরএম",
        merchandise: "পণ্যদ্রব্য",
        active_services_sidebar: "সক্রিয় সার্ভিস",
        order_history: "অর্ডারের ইতিহাস",
        invoices_and_billing: "ইনভয়েস এবং বিলিং",
        product_catalog: "পণ্য ক্যাটালগ",
        white_label_config: "হোয়াইট-লেবেল কনফিগারেশন",
        help_and_support: "সাহায্য এবং সাপোর্ট",
        switch_to_client_view: "ক্লায়েন্ট ভিউতে যান",
        my_commissions: "আমার কমিশন",
        back_to_reseller: "রিসেলারে ফিরে যান",
        profile: "প্রোফাইল",
        add_service: "সার্ভিস যোগ করুন",
        list_all_services: "সব সার্ভিস",
        expiring_services: "মেয়াদ শেষ হচ্ছে",
        support_tickets: "সাপোর্ট টিকেট",
        network_issues_menu: "নেটওয়ার্ক অবস্থা",
        predefined_replies: "প্রি-ডিফাইন্ড উত্তর",
        refunds: "রিফান্ড",
        product_management: "আপনার হোস্টিং প্ল্যান, ডোমেইন এবং বৈশ্বিক ইনভেন্টরি পরিচালনা করুন।",
        create_product: "পণ্য তৈরি করুন",
        product_name: "পণ্যের নাম",
        price: "মূল্য",
        stock: "স্টক",
        list_all_orders: "সব অর্ডার তালিকা",
        add_new_order: "নতুন অর্ডার যোগ করুন",
        invoices: "ইনভয়েস",
        transactions: "লেনদেন",
        billable_items: "বিলের যোগ্য আইটেম",
        quotes: "কোটস",

        // Products
        products: "পণ্য",
        view_all_products: "সব পণ্য দেখুন",
        add_new_product: "নতুন পণ্য যোগ করুন",
        categories: "ক্যাটাগরি",
        add_category: "ক্যাটাগরি যোগ করুন",
        product_description: "আপনার পণ্যের ক্যাটালগ এবং পরিষেবা পরিচালনা করুন।",
        category_name: "ক্যাটাগরির নাম",
        stock_control: "স্টক নিয়ন্ত্রণ",
        taxable: "করযোগ্য",

        // Services & Hosting
        my_services: "আমার সার্ভিসসমূহ",
        services_hub: "আপনার সক্রিয় হোস্টিং প্যাকেজ এবং সার্ভারগুলোর কেন্দ্রীয় হাব।",
        product_service: "পণ্য / সার্ভিস",
        pricing: "মূল্য নির্ধারণ",
        next_due_date: "পরবর্তী প্রদেয় তারিখ",
        order_new_service: "নতুন সার্ভিস অর্ডার করুন",
        find_service_placeholder: "একটি সার্ভিস খুঁজুন...",
        shared_hosting: "শেয়ার্ড হোস্টিং",
        reseller_accounts: "রিসেলার অ্যাকাউন্ট",
        vps_servers: "ভিপিএস/সার্ভার",
        hosting_plans: "হোস্টিং প্ল্যান",
        domain_registration: "ডোমেইন রেজিস্ট্রেশন",
        domains: "ডোমেইন",
        hosting: "হোস্টিং",
        list_all_domains: "সব ডোমেইন তালিকা",
        register_domain: "ডোমেইন রেজিস্ট্রেশন",
        expiring_domains: "মেয়াদোত্তীর্ণ ডোমেইন",
        tld_pricing: "টিএলডি মূল্য নির্ধারণ",
        my_domains: "আমার ডোমেইন",
        buy_new_domain: "নতুন ডোমেইন কিনুন",
        domain_name: "ডোমেইনের নাম",
        registration_date: "নিবন্ধনের তারিখ",
        expiry_date: "মেয়াদ উত্তীর্ণের তারিখ",
        search_domains_placeholder: "ডোমেইন খুঁজুন...",

        // Infrastructure
        infrastructure: "ইনফ্রাস্ট্রাকচার",
        asset_inventory: "সম্পদ ইনভেন্টরি",
        provision_new: "নতুন সার্ভিস যোগ",
        active_nodes: "সক্রিয় নোড",
        system_load: "সিস্টেম লোড",
        deployment_core: "ডেপ্লয়মেন্ট কোর",

        // Store & Cart
        store: "স্টোর",
        cart: "কার্ট",
        checkout: "চেকআউট",

        add_to_cart: "কার্টে যোগ করুন",
        buy_now: "এখন কিনুন",
        empty_cart: "আপনার কার্ট খালি",
        order_summary: "অর্ডার সারাংশ",
        complete_order: "অর্ডার সম্পন্ন করুন",
        new_arrivals: "নতুন আগমন",
        next_gen: "পরবর্তী প্রজন্মের",
        cloud: "ক্লাউড",
        power_digital_future: "এন্টারপ্রাইজ-গ্রেড হোস্টিং এবং নিরবচ্ছিন্ন ডোমেইন ম্যানেজমেন্টের সাথে আপনার ডিজিটাল ভবিষ্যতকে শক্তিশালী করুন।",
        review_cart: "কার্ট চেক করুন",
        secure_checkout_guaranteed: "নিরাপদ চেকআউট গ্যারান্টিযুক্ত",
        starting_at: "শুরু হচ্ছে মাত্র",
        mo: "/মাস",
        initializing_catalog: "ক্যাটালগ লোড হচ্ছে...",
        inventory_items: "ইনভেন্টরি আইটেম",
        billing_identity: "বিলিং প্রোফাইল",
        verify_profile_provisioning: "স্বয়ংক্রিয় পরিষেবা চালুর জন্য আপনার প্রোফাইল তথ্য যাচাই করুন।",
        account_holder: "অ্যাকাউন্ট হোল্ডার",
        email_nexus: "ইমেল কেন্দ্র",
        corporate_org: "কর্পোরেট/প্রতিষ্ঠান",
        leave_blank_individual: "ব্যক্তিগত ব্যবহারের জন্য খালি রাখুন",
        nexus_address: "বিলিং ঠিকানা",
        global_hq: "গ্লোবাল হেডকোয়ার্টার বা আবাসিক ঠিকানা",
        automated_kyc: "স্বয়ংক্রিয় কেওয়াইসি স্বীকৃতি",
        identity_preverified: "আপনার পরিচয় পূর্ব-যাচাইকৃত। এই অর্ডারের জন্য আর কোনো নথি জমা দেওয়ার প্রয়োজন নেই।",
        select_protocol: "লেনদেনের পদ্ধতি নির্বাচন করুন",
        credit_interface: "ক্রেডিট ইন্টারফেস",
        instant_deployment: "ভিসা, মাস্টারকার্ড, অ্যামেক্স • তাৎক্ষণিক অ্যাক্টিভেশন",
        mobile_gateway: "মোবাইল গেটওয়ে",
        bkash_stripe_oneclick: "বিকাশ, নগদ, স্ট্রাইপ মোবাইল • ১-ক্লিক পেমেন্ট",
        encrypted_lock: "এন্ড-টু-এন্ড এনক্রিপ্টেড",
        authorize_resources: "এগিয়ে যাওয়ার মাধ্যমে, আপনি ডাব্লুএইচএমসিএস ফিউশনকে অনুরোধকৃত পরিষেবাগুলি অবিলম্বে চালু করার অনুমতি দিচ্ছেন।",
        deploy_assets_now: "এখনই একটিভ করুন",
        refine_details: "বিস্তারিত তথ্য",
        deployment_initialized: "ডিপ্লয়মেন্ট শুরু হয়েছে",
        order_broadcast: "অর্ডারটি আমাদের অটোমেশন ইঞ্জিনে পাঠানো হয়েছে।",
        workspace_home: "ওয়ার্কস্পেস হোম",
        manage_assets: "সম্পদ পরিচালনা",
        financial_overview: "আর্থিক ওভারভিউ",
        net_payable: "মোট প্রদেয়",
        promo_credentials: "প্রমোশন কোড",
        voucher_promo: "ভাউচার বা প্রমো...",
        pci_compliant: "পিসিআই-ডিএসএস কমপ্লায়েন্ট গেটওয়ে",
        ssl_secure: "এসএসএল সিকিউর সার্টিফিকেট",
        secure_transaction: "নিরাপদ লেনদেন",
        finalize_your: "আপনার অর্ডার",
        moments_away_deploy: "আপনি আপনার ক্লাউড ওয়ার্কস্পেস চালুর অতি সন্নিকটে।",
        add_premium_infra: "চেকআউট চালিয়ে যেতে আপনার ইনভেন্টরিতে কিছু প্রিমিয়াম সার্ভিস যোগ করুন।",
        browse_store: "স্টোর দেখুন",
        tax_vat: "কর/ভ্যাট",
        scheduled_maintenance_maintenance: "আগামী ৫ই জানুয়ারি টোকিও অঞ্চলে নির্ধারিত নেটওয়ার্ক আপগ্রেড। কোনো প্রভাব প্রত্যাশিত নয়।",
        reseller_dashboard: "রিসেলার ড্যাশবোর্ড",
        reseller_center: "রিসেলার সেন্টার",
        commissions: "কমিশন",
        payouts: "পেমেন্ট",
        white_label: "হোয়াইট লেবেল",
        treasury: "ট্রেজারি",
        payout_requests: "পেমেন্ট অনুরোধ",
        available_balance: "বর্তমান ব্যালেন্স",
        withdraw_funds: "টাকা উত্তোলন",
        payout_history: "পেমেন্ট ইতিহাস",
        bdt: "বিডিটি",
        taka: "টাকা",

        // Settings & Security
        branding_settings: "ব্র্যান্ডিং সেটিংস",
        visual_identity: "ভিজুয়াল আইডেন্টিটি",
        interface_personality: "ইন্টারফেস পারসোনালিটি",
        theme_modes: "থিম মোড",
        media_assets: "মিডিয়া অ্যাসেটস",
        domain_seo: "ডোমেইন এবং এসইও",
        custom_dev: "কাস্টম ডেভ",
        live_preview: "লাইভ প্রিভিউ",
        system_configuration: "সিস্টেম কনফিগারেশন",
        general: "সাধারণ",
        security: "নিরাপত্তা",
        my_profile: "আমার প্রোফাইল",
        audit_history: "অডিট ইতিহাস",
        audit_history_desc: "আপনার অ্যাকাউন্টের অডিট ইতিহাস।",

        // Utilities & Security (Sidebar)
        utilities: "ইউটিলিটি",
        whois_lookup: "হু-ইজ লুকআপ",
        dns_resolver: "ডিএনএস সমাধানকারী",
        tld_sync: "টিএলডি সিঙ্ক",
        activity_logs: "ক্রিয়াকলাপ লগ",
        banned_ips: "নিষিদ্ধ আইপি",
        security_questions: "নিরাপত্তা প্রশ্ন",

        // Activity Logs
        activity_protocol: "অ্যাক্টিভিটি প্রোটোকল",
        technical_narrative: "প্রযুক্তিগত বর্ণনা",
        author: "লেখক",
        timestamp: "সময়কাল",
        trace: "ট্রেস",
        log_engine_desc: "সমস্ত প্রশাসনিক এবং সিস্টেম-ব্যাপী গোয়েন্দা তথ্যের অপরিবর্তনীয় কালানুক্রমিক রেকর্ড।",
        search_logs_placeholder: "অ্যাকশন, ব্যবহারকারী বা আইপি দ্বারা অনুসন্ধান করুন...",
        advanced_filters: "উন্নত ফিল্টার",
        aggregating_logs: "বৈশ্বিক কার্যকলাপ প্রোটোকল একত্রিত করা হচ্ছে...",
        activity_stream: "অ্যাক্টিভিটি স্ট্রিম",

        // Public Pages & Landing (Bangla)
        home: "হোম",
        about_us: "আমাদের সম্পর্কে",
        contact_us: "যোগাযোগ",
        privacy_policy: "গোপনীয়তা নীতি",
        terms_of_service: "শর্তাবলী",
        features: "বৈশিষ্ট্য",
        testimonials: "প্রশংসাপত্র",
        faq: "প্রশ্নোত্তর",
        get_started: "শুরু করুন",
        learn_more: "আরও জানুন",

        // Hero Section
        hero_badge: "অপারেশনাল এবং সুরক্ষিত",
        hero_title_1: "আপনার ডিজিটাল সাম্রাজ্য",
        hero_title_accent: "আজই গড়ে তুলুন",
        hero_subtitle: "প্রিমিয়াম ওয়েব হোস্টিং, ভিপিএস এবং ডেডিকেটেড সার্ভার ৯৯.৯% আপটাইম গ্যারান্টি এবং ২৪/৭ বিশেষজ্ঞ সহায়তার সাথে।",
        hero_search_placeholder: "আপনার পছন্দের ডোমেইন খুঁজুন...",
        hero_search_btn: "সার্চ",
        retention_reputation: "রিটেনশনই আমাদের রেপুটেশন: দীর্ঘদিন ধরে চলা লয়াল ক্লায়েন্ট বেস আমাদের সবচেয়ে বড় প্রমাণ।",
        verify_buy: "যাচাই করুন: Live Benchmark রিপোর্ট দেখুন, Backup সিস্টেম দেখুন—তারপর সিদ্ধান্ত নিন।",
        professional_support: "প্রফেশনাল সাপোর্টই আমাদের ইম্প্রেশন",

        // Service Group
        choose_solution: "আপনার হোস্টিং সলিউশন বেছে নিন",
        solution_desc: "গতি এবং নির্ভরযোগ্যতার জন্য তৈরি আমাদের প্রতিযোগিতামূলক মূল্য তালিকা দেখতে একটি বিভাগ নির্বাচন করুন।",
        plans_available: "টি প্ল্যান উপলব্ধ",
        see_plans: "প্ল্যানগুলো দেখুন",
        back_to_categories: "ক্যাটাগরিতে ফিরে যান",
        no_plans_available: "এই ক্যাটাগরিতে বর্তমানে কোনো প্ল্যান উপলব্ধ নেই।",

        // Pricing Card
        order_now: "এখনই অর্ডার করুন",
        starter_journey: "আপনার যাত্রা শুরু করার জন্য পারফেক্ট",

        // Features Section (Bangla)
        why_choose_us: "কেন আমাদের বেছে নেবেন",
        why_choose_desc: "আমরা এন্টারপ্রাইজ-গ্রেড অবকাঠামো সহ সেরা হোস্টিং সমাধান প্রদান করি।",
        feature_speed_title: "ফাস্ট BDIX অপ্টিমাইজড NVMe",
        feature_speed_desc: "লোকাল ভিজিটরদের জন্য সাইট লোড গতি নিশ্চিত করতে BDIX অপ্টিমাইজড NVMe SSD স্টোরেজ।",
        feature_security_title: "কঠোর নিরাপত্তা",
        feature_security_desc: "উন্নত DDoS সুরক্ষা, Imunify360 এবং প্রতি ঘন্টায় স্বয়ংক্রিয় ডেটাবেস ব্যাকআপ।",
        feature_support_title: "প্রফেশনাল সাপোর্ট",
        feature_support_desc: "শুধু সাপোর্ট এজেন্ট নয়, ইঞ্জিনিয়ারদের সাপোর্ট পাচ্ছেন ২৪/৭ বাংলা এবং ইংরেজিতে।",
        feature_uptime_title: "স্বচ্ছ আপটাইম",
        feature_uptime_desc: "আমরা লাইভ বেঞ্চমার্ক রিপোর্ট প্রদান করি যাতে আপনি আমাদের প্রকৃত পারফরম্যান্স দেখতে পারেন।",

        // Testimonials
        trusted_by: "ডেভেলপারদের দ্বারা বিশ্বস্ত",
        testimonial_1: "সেরা হোস্টিং প্রোভাইডার। সাপোর্ট অসাধারণ!",
        testimonial_2: "মাইগ্রেশন খুব সহজ ছিল এবং আমার সাইট এখন ৩ গুণ দ্রুত।",

        // FAQ
        faq_title: "সচরাচর জিজ্ঞাসিত প্রশ্ন",
        faq_1_q: "অ্যাক্টিভেট হতে কত সময় লাগে?",
        faq_1_a: "পেমেন্ট নিশ্চিতকরণের পর বেশিরভাগ সার্ভিস তাৎক্ষণিকভাবে চালু হয়।",
        faq_2_q: "আমি কি পরে প্ল্যান আপগ্রেড করতে পারি?",
        faq_2_a: "হ্যাঁ, আপনি ক্লায়েন্ট এরিয়া থেকে যেকোনো সময় প্ল্যান আপগ্রেড বা ডাউনগ্রেড করতে পারেন।",
        faq_3_q: "আপনারা কি মানি-ব্যাক গ্যারান্টি দেন?",
        faq_3_a: "হ্যাঁ, আমরা সকল শেয়ার্ড হোস্টিং প্ল্যানে ৩০ দিনের মানি-ব্যাক গ্যারান্টি দিই।",

        // Contact
        get_in_touch: "যোগাযোগ করুন",
        contact_desc: "প্রশ্ন আছে? আমরা সাহায্য করতে প্রস্তুত।",
        send_message: "মেসেজ পাঠান",
        your_name: "আপনার নাম",
        your_email: "আপনার ইমেল",
        subject: "বিষয়",
        message: "মেসেজ",
        address: "ঠিকানা",
        phone: "ফোন",

        // Legal
        last_updated: "সর্বশেষ আপডেট",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>("en");

    // Clear saved language preference to ensure consistency after removing the toggle
    useEffect(() => {
        document.documentElement.lang = "en";
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("language", lang);
        document.documentElement.lang = lang;
    };

    const toggleLanguage = () => {
        setLanguage(language === "en" ? "bn" : "en");
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
