"use client";

import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { ShieldCheck, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useRouter } from "next/navigation";

const otpSchema = z.object({
    code: z.string().length(6, "Code must be 6 digits"),
});

export default function TwoFactorPage() {
    const router = useRouter();
    const { register, handleSubmit, formState: { errors } } = useForm<{ code: string }>({
        resolver: zodResolver(otpSchema),
    });

    const onSubmit = (data: { code: string }) => {
        console.log("Verifying 2FA Login:", data.code);
        router.push("/dashboard");
    };

    return (
        <div className="min-h-screen flex items-center justify-center p-6 glass-darker">
            <div className="w-full max-w-sm glass rounded-3xl p-8 space-y-6">
                <div className="text-center">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 text-primary mb-4">
                        <ShieldCheck className="w-8 h-8" />
                    </div>
                    <h1 className="text-2xl font-bold">2-Step Verification</h1>
                    <p className="text-muted-foreground text-sm mt-2">Enter the verification code generated by your authenticator app.</p>
                </div>

                <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
                    <div className="space-y-2">
                        <Input
                            autoFocus
                            placeholder="000 000"
                            className="text-center text-3xl h-14 tracking-[0.5em] font-mono bg-background/50"
                            maxLength={6}
                            {...register("code")}
                        />
                        {errors.code && <p className="text-destructive text-center text-xs">{errors.code.message}</p>}
                    </div>

                    <Button type="submit" className="w-full h-12 text-lg">
                        Verify <ArrowRight className="ml-2 w-5 h-5" />
                    </Button>
                </form>

                <div className="text-center">
                    <button className="text-xs text-muted-foreground hover:text-primary transition-colors">
                        Lost your device? Use recovery code
                    </button>
                </div>
            </div>
        </div>
    );
}
